import { Property } from './Property';
import { Image } from './image';

export class Vehicle {
  ID: number;
  AddDate: Date;
  AdStatus: string;
  BrandName: string;
  CategAlias: string;
  CategID: number;
  CategName: string;
  CategNameMultiLang: string;
  CityAlias: string;
  CityName: string;
  CityNameMultiLang: string;
  CombinedProperties?: any;
  Comment?: any;
  CommentRestriction: string;
  Condition: string;
  ConvertedCurrencySymbol?: any;
  ConvertedPrice: string;
  CurrencyFullName: string;
  CurrencyName: string;
  CurrencySymbol: string;
  DateExpired: Date;
  Description: string;
  FolderImgName: string;
  HotSelling: boolean;
  ImagePath: string;
  Images: Image[];
  ImgExists: boolean;
  IsAutoUpdatable: string;
  IsExpired: boolean;
  MainImg: string;
  MainImgMiddle: string;
  MainImgSuperSmall: string;
  MapJsonCoordList: any[];
  ModelName: string;
  ModirationStatus: string;
  OtherConvertedPrice: string;
  Price: number;
  Properties: Property[];
  SeoTitle: string;
  Services: any[];
  ShortDescription: string;
  Title: string;
  TypeName: string;
  ViewCount: number;
  Year: string;
}
